name: Various Bukkit Modifications
main: com.github.yofel.bukkit_modifications.Mods
version: 0.6
commands:
    mcspeed:
        description: set the Minecart speed for new minecarts
        usage: /mcspeed [speed]
        permission: bukkit_modifications.mcspeed
        permission-message: You have insufficient permissions for bukkit_modifications.mcspeed
permissions:
    bukkit_modifications.potion_stacking:
        description: gives permission to stack potions
        default: op
